spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atm_database?serverTimezone=Europe/Bucharest
    username: postgres
    password: Senila1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Bucharest
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port : 8082
